/**
 * Slide URLs come from `new-kids-webp-manifest.json`, generated by
 * `npm run images:new-kids` (sources: `New kids in town/*.png`).
 */
import manifest from './new-kids-webp-manifest.json'
import { publicUrl } from '../utils/publicUrl'

export type NewKidsSlide = { src: string; alt: string }

export const newKidsProductSlides: NewKidsSlide[] = manifest.slides.map((rel, i) => ({
  src: publicUrl(rel),
  alt: `Long Shots Pizza — product ${i + 1}`,
}))
